### ISSUE TITLE
Can't install plugins

### ISSUE THREAD

**Issue by juanignaciosl** [ramr/redmine-2.0-openshift-quickstart#5]
I am trying to install plugins but they won't appear at administration --> information, no matter what I do.

I first thought it was a matter of [redmine_charts2](https://github.com/pharmazone/redmine_charts2/issues/3#issuecomment-10270485) but pharmazone helped me and it was obvious I'm doing something wrong (or there's a problem with redmine 2 at OpenShift).

This is my problem: I follow plugin installation instructions (script/rails plugin install, rake, commit, push) but plugins don't appear.

The only thing i've not done to the letter is rake migration. Since I don't run Redmine locally, when I perform any migration I change config/database.yml. I change production config, which has variables like $OPENSHIFT_DB_HOST to OpenShift remote database. After running the migration I checkout it to its original state.

Redmine 2.0.3.stable

Default administrator account changed -- yes
Attachments directory writable -- yes
Plugin assets directory writable -- yes
RMagick available (optional) -- yes

Environment:
Redmine version 2.0.3.stable
Ruby version 1.9.3 (x86_64-linux)
Rails version 3.2.6
Environment production
Database adapter Mysql2
Redmine plugins:
no plugin installed

**Comment by ramr** [comment]
Thanks for reporting this. Hmm, odd haven't got notifications from this github repo (haven't looked at it in a while). I'll take a look at updating it sometime later this week.

**Comment by ramr** [comment]
I just updated Redmine to version 2.6.0 - needs Ruby 1.9+ version though. Can you please check if it works for you now. You will need to create a new app (ruby-1.9 though). Thanks.
