### ISSUE TITLE
post_deploy error condition in 23 line don't work

### ISSUE THREAD

**Issue by kaaboeld** [ramr/redmine-2.0-openshift-quickstart#8]
/.openshift/action_hooks/post_deploy

in 23 line:
if ! /usr/bin/mysql -h "$OPENSHIFT_MYSQL_**MYSQL_MYSQL**_DB_HOST"  \

**Comment by ramr** [comment]
Thanks for reporting that. Fixed - judicious use of '.' in vi!! ;^)
